import type { PreviousQuotation } from "../pages/travels/createTravels/interfaces/Quotation";

export const mockPreviousQuotes: PreviousQuotation[] = [
    {
        id: 'Q001',
        customer: { id: 'C001', name: 'Sarah Johnson', email: 'sarah@email.com' },
        destinations: ['Rome', 'Florence', 'Venice'],
        createdAt: '2024-10-15',
        totalValue: 2850,
        currency: 'EUR',
        duration: 7,
        travelers: 2,
        status: "approved",
        agent: 'John Smith',
        tags: ['honeymoon', 'luxury'],
        version: 2,
    },
    {
        id: 'Q002',
        customer: { id: 'C002', name: 'Mike Chen', email: 'mike@email.com' },
        destinations: ['Barcelona', 'Madrid'],
        createdAt: '2024-10-12',
        totalValue: 1950,
        currency: 'EUR',
        duration: 5,
        travelers: 4,
        status: "sent",
        agent: 'Emma Wilson',
        tags: ['family', 'cultural'],
        version: 1,
    },
    {
        id: 'Q003',
        customer: { id: 'C003', name: 'Anna Mueller', email: 'anna@email.com' },
        destinations: ['Paris', 'Lyon'],
        createdAt: '2024-10-10',
        totalValue: 3200,
        currency: 'EUR',
        duration: 6,
        travelers: 2,
        status: 'sent',
        agent: 'John Smith',
        tags: ['luxury', 'gourmet'],
        version: 3,
    },
];